### PR TITLE
[ROS2] Windows bringup.

### PR DESCRIPTION
**Pull request by seanyen**
This pull request is to enable `control_toolbox` to be built against Foxy Windows release.

* Defined `_USE_MATH_DEFINES` for math constants.
* Defined visibility header for `control_toolbox`.

### CODE REVIEW

**Comment by bmagyar** [comment]
@seanyen I've made a PR against your branch fixing the CI. I am not going to spend time reviewing legal texts for the CLA, please either cherry-pick it or merge it without my signature.

**Comment by seanyen** [comment]
Now the CI failed at the error: Is it a known issue?

```
2021-01-04T20:36:46.7218405Z In file included from /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/src/realtime_clock.cpp:39:0:
2021-01-04T20:36:46.7221160Z /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/include/realtime_tools/realtime_clock.h:93:35: warning: ‘rclcpp::Duration::Duration(rcl_duration_value_t)’ is deprecated: Use Duration::from_nanoseconds instead or std::chrono_literals. For example:rclcpp::Duration::from_nanoseconds(int64_variable);rclcpp::Duration(0ns); [-Wdeprecated-declarations]
2021-01-04T20:36:46.7222918Z    rclcpp::Duration clock_offset_{0};
2021-01-04T20:36:46.7223416Z                                    ^
2021-01-04T20:36:46.7224158Z In file included from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/time.hpp:24:0,
2021-01-04T20:36:46.7225203Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/clock.hpp:23,
2021-01-04T20:36:46.7226295Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/include/realtime_tools/realtime_clock.h:45,
2021-01-04T20:36:46.7227356Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/src/realtime_clock.cpp:39:
2021-01-04T20:36:46.7228618Z /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/duration.hpp:46:12: note: declared here
2021-01-04T20:36:46.7229773Z    explicit Duration(rcl_duration_value_t nanoseconds);
2021-01-04T20:36:46.7230322Z             ^~~~~~~~
2021-01-04T20:36:46.7231932Z /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/src/realtime_clock.cpp: In member function ‘rclcpp::Time realtime_tools::RealtimeClock::now(const rclcpp::Time&)’:
2021-01-04T20:36:46.7235057Z /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/src/realtime_clock.cpp:81:39: warning: ‘rclcpp::Duration::Duration(rcl_duration_value_t)’ is deprecated: Use Duration::from_nanoseconds instead or std::chrono_literals. For example:rclcpp::Duration::from_nanoseconds(int64_variable);rclcpp::Duration(0ns); [-Wdeprecated-declarations]
2021-01-04T20:36:46.7236898Z        rclcpp::Duration period_offset(0);
2021-01-04T20:36:46.7237365Z                                        ^
2021-01-04T20:36:46.7238162Z In file included from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/time.hpp:24:0,
2021-01-04T20:36:46.7239302Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/clock.hpp:23,
2021-01-04T20:36:46.7240476Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/include/realtime_tools/realtime_clock.h:45,
2021-01-04T20:36:46.7241633Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/src/realtime_clock.cpp:39:
2021-01-04T20:36:46.7242809Z /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/duration.hpp:46:12: note: declared here
2021-01-04T20:36:46.7243797Z    explicit Duration(rcl_duration_value_t nanoseconds);
2021-01-04T20:36:46.7244351Z             ^~~~~~~~
2021-01-04T20:36:46.7245145Z In file included from /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/test/realtime_clock_tests.cpp:36:0:
2021-01-04T20:36:46.7248168Z /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/include/realtime_tools/realtime_clock.h:93:35: warning: ‘rclcpp::Duration::Duration(rcl_duration_value_t)’ is deprecated: Use Duration::from_nanoseconds instead or std::chrono_literals. For example:rclcpp::Duration::from_nanoseconds(int64_variable);rclcpp::Duration(0ns); [-Wdeprecated-declarations]
2021-01-04T20:36:46.7250086Z    rclcpp::Duration clock_offset_{0};
2021-01-04T20:36:46.7250558Z                                    ^
2021-01-04T20:36:46.7251347Z In file included from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/time.hpp:24:0,
2021-01-04T20:36:46.7252592Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/clock.hpp:23,
2021-01-04T20:36:46.7253910Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/include/realtime_tools/realtime_clock.h:45,
2021-01-04T20:36:46.7255098Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/test/realtime_clock_tests.cpp:36:
2021-01-04T20:36:46.7256298Z /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/duration.hpp:46:12: note: declared here
2021-01-04T20:36:46.7257355Z    explicit Duration(rcl_duration_value_t nanoseconds);
2021-01-04T20:36:46.7257899Z             ^~~~~~~~
2021-01-04T20:36:46.7258676Z In file included from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/client.hpp:40:0,
2021-01-04T20:36:46.7259858Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/callback_group.hpp:23,
2021-01-04T20:36:46.7261049Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/any_executable.hpp:20,
2021-01-04T20:36:46.7262229Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/memory_strategy.hpp:25,
2021-01-04T20:36:46.7263530Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/memory_strategies.hpp:18,
2021-01-04T20:36:46.7264662Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/executor_options.hpp:20,
2021-01-04T20:36:46.7265747Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/executor.hpp:35,
2021-01-04T20:36:46.7266887Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/executors/multi_threaded_executor.hpp:25,
2021-01-04T20:36:46.7268059Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/install/rclcpp/include/rclcpp/executors.hpp:21,
2021-01-04T20:36:46.7269161Z                  from /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/test/realtime_server_goal_handle_tests.cpp:39:
2021-01-04T20:36:46.7271407Z /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/include/realtime_tools/realtime_server_goal_handle.h: In member function ‘void realtime_tools::RealtimeServerGoalHandle<Action>::runNonRealtime()’:
2021-01-04T20:36:46.7274284Z /home/runner/work/control_toolbox/control_toolbox/ros_ws/src/realtime_tools/include/realtime_tools/realtime_server_goal_handle.h:167:7: error: cannot convert ‘const string {aka const std::__cxx11::basic_string<char>}’ to ‘const char*’ for argument ‘4’ to ‘void rcutils_log(const rcutils_log_location_t*, int, const char*, const char*, ...)’
2021-01-04T20:36:46.7275836Z        RCLCPP_WARN(logger_, e.formatted_message);
2021-01-04T20:36:46.7276305Z        ^
2021-01-04T20:36:46.7277022Z make[2]: *** [CMakeFiles/realtime_server_goal_handle_tests.dir/test/realtime_server_goal_handle_tests.cpp.o] Error 1
2021-01-04T20:36:46.7277988Z make[1]: *** [CMakeFiles/realtime_server_goal_handle_tests.dir/all] Error 2
```

**Comment by bmagyar** [comment]
Thanks for the update, definitely not a know issue... I wonder how it happened in the first place, this package has been released to Foxy et al for a while...

**Comment by bmagyar** [comment]
Thank you, I'll merge this and see your other PR

**Pull request merged**
