### PR TITLE
Added LeadLag controller

### PR DESCRIPTION
**Pull request by progtologist**
This PR should be able to be integrated in any version(branch), I am currently using indigo so I have only tested it against that.

### CODE REVIEW

**Comment by progtologist** [comment]
This also partially addresses issue #35

**Comment by bmagyar** [comment]
* Could you please squash the 2 commits so we don't have a broken state on the history?
* Do you have examples of where you use this already perhaps? I'm looking for something visual people could try.

**Comment by progtologist** [comment]
@bmagyar I just squashed all the commits into one.
As far as the examples go, I am planning on developing some controllers in the next days for ros_controllers using this LeadLag class.

**Comment by progtologist** [comment]
The latest commit refers to issue #61 (would have preferred to branch them out, but I guess it's a little bit too late now).

**Comment by graiola** [comment]
Hello,

Thanks for the pr!
I went through the code and it seems good to me, but I would prefer to merge it on kinetic. Could you prepare a pr for it?

Some (very) minor notes about the documentation :)
- `\f$ G(s) = gain * \frac{1 + \frac{w}{w_z}}{1 + \frac{w}{w_p}} \f$`
in the formula should be s and not w, right?
- It should be highlighted that dt has to be the same as the sample time in the controller.

Thanks again! :+1:

**Comment by bmagyar** [comment]
It's never not too late to branch it out. You can easily roll back your PR branch to the previous commit and make a force push. I'd merge the travis update on the separate PR.

You should be able to change the Pull Request target to kinetic-devel.

**Comment by bmagyar** [comment]
@progtologist Could you please rebase this PR against kinetic? Now we've got travis working again

**Comment by progtologist** [comment]
I will try to do it this weekend and update you ;)

**Comment by bmagyar** [comment]
@progtologist this is a kind ping. I'd like to merge this, believe me :)

**Comment by progtologist** [comment]
I am closing this PR in favor of #68 (switched to kinetic, created separate feature branch to avoid polution if another fix emerges)

**Pull request closed without merging**
