### PR TITLE
Use Eigen CMake target

### LINKED ISSUE #178: RHEL 8 build with eigen
We have a compilation issue on RHEL 8 with eigen:
https://github.com/ros-controls/control_toolbox/actions/runs/7784307246/job/21224592892?pr=177

Maybe we should consider linking against it as outlined here
https://github.com/PickNikRobotics/RSL/issues/114

### PR DESCRIPTION
**Pull request by christophfroehlich**
I changed the CMake file to use Eigen's CMake target as described here https://eigen.tuxfamily.org/dox/TopicCMakeGuide.html

This fixes #178 for RHEL 8

### CODE REVIEW

**Comment by saikishor** [comment]
@christophfroehlich is this missing a test_msgs dependency?

**Comment by christophfroehlich** [comment]
No, rosdep fails for realtime_tools (see also https://github.com/ros-controls/realtime_tools/pull/154)
` [MIRROR] ros-humble-test-msgs-1.2.1-1.el8.20231117.182020.x86_64.rpm: Status code: 404 for http://packages.ros.org/ros2/rhel/8/x86_64/Packages/r/ros-humble-test-msgs-1.2.1-1.el8.20231117.182020.x86_64.rpm (IP: 140.211.166.134)`
I'm already debugging why, when I run it locally it installs ros-humble-test-msgs-1.2.1-1.el8.20240217.042201.x86_64 which is fine, maybe it's because metadata were updated 

> Last metadata expiration check: 22:01:48 ago on Fri Feb 23 00:55:05 2024.

I'm already building new docker containers, if this fixes it I'll add the missing `apt update`-equivalent to the rhel build.

**Comment by saikishor** [comment]
Awesome!

**Review by bmagyar — APPROVED** [review]

**Comment by christophfroehlich** [comment]
The RHEL job still needs an update https://github.com/ros-controls/ros2_control_ci/pull/19

**Review by saikishor — APPROVED** [review]

**Pull request merged**
