### PR TITLE
Update documentation to reflect ROS 2 usage

### PR DESCRIPTION
**Pull request by roncapat**
```cpp
  rclcpp::Time last_time = get_clock()->now();
  while (true) {
    rclcpp::Time time = get_clock()->now();
    double effort = pid.computeCommand(position_desi_ - currentPosition(), (time - last_time).nanoseconds());
    last_time = time;
}
```

### CODE REVIEW

**Comment by roncapat** [comment]
@bmagyar may I ask a brief review?

**Comment by roncapat** [comment]
@christophfroehlich @destogl tagging you since I saw you involved in recent commits :) this should be a very quick thing IMHO. Could you give a look please?

**Review by christophfroehlich — APPROVED** [review]
Thanks for the update!

**Review by destogl — APPROVED** [review]
Great! Thanks!

**Pull request merged**
