### PR TITLE
[WIP] Port to dashing

### PR DESCRIPTION
**Pull request by sloretz**
Opening PR for visibility. This is a super rough port of just the PID class (without porting the parameters) to Dashing. I intend to do more, and it will probably mean smaller PRs ahead of this one, but I want a place to put notes.

* Refactoring PID #55 to separate ROS stuff from math would make porting much easier
* Would be nice if service was in a different package `control_toolbox_interfaces` so it could be a member of the interfaces group without pulling in a bunch of dependencies
* Would be nice if `tune_pid.py` was a C++ executable or in a python package for setuptools entrypoints to make it friendlier to windows

### CODE REVIEW

**Comment by bmagyar** [comment]
I've created a dashing-devel branch, the CI will need updating in this MR too.

**Comment by bmagyar** [comment]
@sloretz can you update us on this one please?

**Comment by sloretz** [comment]
> @sloretz can you update us on this one please?

Unfortunately my time got switched to another task. I don't expect to pick this up again any time soon :-(

**Comment by Karsten1987** [comment]
@sloretz we've briefly talked about this offline. Can this be closed?

**Comment by sloretz** [comment]
Closing in favor of #83

**Pull request closed without merging**
