### PR TITLE
noetic with tinyxml2

### PR DESCRIPTION
**Pull request by akshay-ram-pp**
Control toolbox with ROS Noetic and Tinyxml2 library

### CODE REVIEW

**Comment by bmagyar** [comment]
What are you trying to achieve with this PR?

**Comment by akshay-ram-pp** [comment]
> What are you trying to achieve with this PR?
I wanted to use the control toolbox with latest tinyxml2 library, because tinyxml (older version) source code is not available or updated. i also wanted to use it to build ROS Noetic from source.

**Comment by bmagyar** [comment]
Why? Building on 22.04?

You filed this pull request against the ros2 master branch. I'll readjust and let's see

**Comment by akshay-ram-pp** [comment]
> Why? Building on 22.04?
> 
> You filed this pull request against the ros2 master branch. I'll readjust and let's see

For building  ROS from source on  yocto linux

**Comment by destogl** [comment]
This doesn't look right. so many chnages.

**Comment by akshay-ram-pp** [comment]
> This doesn't look right. so many chnages.



> This doesn't look right. so many chnages.

**Comment by akshay-ram-pp** [comment]
> This doesn't look right. so many chnages.

i have tested it and found working for me.

**Comment by bmagyar** [comment]
@akshay-ram-pp that is a classic recipe for disaster ;) let's do this in a different way. I'll create a new branch called noetic-devel, please submit a PR against that with *a single commit*. 

I was trying to figure out what's so wrong with this PR and I think you simply copied a noetic/melodic version on top of the ros2-master branch and you jammed all those changes in until it worked for you. That's fine, however unfortunately it's unmergeable, we can't even have a meaningful discussion as the changelog is full of irrelevant changes.

**Pull request closed without merging**
