### PR TITLE
Remove code repetition

### PR DESCRIPTION
**Pull request by paulbovbel**
Remove code repetition by collapsing deprecated computeCommand into negative updatePid function call

### CODE REVIEW

**Comment by paulbovbel** [comment]
Trailing whitespace got trimmed, see https://github.com/ros-controls/control_toolbox/pull/46/files?w=1

**Comment by adolfo-rt** [comment]
Although practically the effect would be the same right now, I would strongly recommend providing the patch the other way around: keep the details in `computeCommand`, and implement `updatePid` in terms of `-computeCommand`. The reason being that [`updatePid`](https://github.com/ros-controls/control_toolbox/blob/indigo-devel/include/control_toolbox/pid.h#L305-L321) is deprecated, and might go away some day. It'll be much easier to remove it if it does not contains the actual implementation.

Also, I'm fine with the whitespace fix, but prefer it in a separate commit. I would suggest to first apply that change on the vanilla file, make a style commit, and then proceed to apply the actual code changes.

**Comment by paulbovbel** [comment]
Ah, mixed up which one is deprecated, thanks

**Comment by adolfo-rt** [comment]
Thanks @paulbovbel. Ready to merge!

**Pull request merged**
